### ISSUE TITLE
A question on permissibleLeftShift

### ISSUE THREAD

**Issue by HJoonKwon** [zcaicaros/L2S#2]
If my understanding about the state initialization for the training is correct, you are using a simple classical heuristic method to obtain the initial solution. Regarding that process, you implemented ```_rules_solver``` and ```permissibleLeftShift``` to validate an action proposed. Even though ```permissibleLeftShift``` returns a flag, which validates whether the action is legal or not, I don't see any part of the initialization process using that flag to validate actions. Was it intended? If it was, could you please explain why? 
Thank you!

**Comment by zcaicaros** [comment]
I saw this issue is closed, which may be because the issue was resolved by the proposer. It may be re-opened if there are still questions.
